# permissions for end users to edit podflames.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podflame-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: profile-pod-operator
    app.kubernetes.io/part-of: profile-pod-operator
    app.kubernetes.io/managed-by: kustomize
  name: podflame-editor-role
rules:
- apiGroups:
  - profilepod.io
  resources:
  - podflames
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - profilepod.io
  resources:
  - podflames/status
  verbs:
  - get
